problema que apareceu no LogCat
2021-05-18 14:59:00.670 5563-5588/com.tarefagameandroid.game E/AndroidRuntime: FATAL EXCEPTION: GLThread 308
    Process: com.tarefagameandroid.game, PID: 5563
    java.lang.NullPointerException: Attempt to invoke virtual method 'int com.badlogic.gdx.graphics.Texture.getWidth()' on a null object reference
        at com.badlogic.gdx.graphics.g2d.SpriteBatch.draw(SpriteBatch.java:503)
        at com.tarefagameandroid.game.Jogo.desenharTexturas(Jogo.java:146)
        at com.tarefagameandroid.game.Jogo.render(Jogo.java:109)
        at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:471)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
2021-05-18 14:59:04.681 5563-5563/com.tarefagameandroid.game E/AndroidGraphics: waiting for pause synchronization took too long; assuming deadlock and killing
2021-05-18 14:59:04.681 5563-5563/com.tarefagameandroid.game I/Process: Sending signal. PID: 5563 SIG: 9