Erro anterior corrigido, era a variavel com nome errado. agora temos esse erro
E/AndroidRuntime: FATAL EXCEPTION: GLThread 328
    Process: com.tarefagameandroid.game, PID: 6144
    java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
        at com.tarefagameandroid.game.Jogo.desenharTexturas(Jogo.java:144)
        at com.tarefagameandroid.game.Jogo.render(Jogo.java:109)
        at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:471)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
E/AndroidGraphics: waiting for pause synchronization took too long; assuming deadlock and killing